"use client";

import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { authenticatedFetch } from "@/lib/supabase";
import type { PoleRecord } from "@/lib/portal-types";

export default function PoleReportPage() {
  const params = useParams<{ projectId: string; poleId: string }>();
  const [record, setRecord] = useState<{ pole: PoleRecord; project: { name: string; client_name: string } } | null>(null);
  const [error, setError] = useState("");
  useEffect(() => { let active = true; void authenticatedFetch(`/api/projects/${encodeURIComponent(params.projectId)}/poles`).then((response) => response.json()).then((payload) => { const pole = payload.poles?.find((item: PoleRecord) => item.id === params.poleId); if (!pole) throw new Error("Pole not found"); if (active) setRecord({ pole, project: payload.project }); }).catch((err) => { if (active) setError(err instanceof Error ? err.message : "Could not load pole report"); }); return () => { active = false; }; }, [params.projectId, params.poleId]);
  if (!record) return <main className="report-page"><p>{error || "Loading report…"}</p></main>;
  const { pole, project } = record;
  return <main className="report-page"><article className="report-document"><header className="report-header"><div><b>POWERTEK • POLE INTELLIGENCE</b><h1>{pole.poleName}</h1><p>{project.client_name} / {project.name}</p></div><button className="orange-button no-print" onClick={() => window.print()}>Print / Save PDF</button></header><section className="report-metrics"><ReportMetric label="Latitude" value={String(pole.latitude)} /><ReportMetric label="Longitude" value={String(pole.longitude)} /><ReportMetric label="Ground elevation" value={`${pole.elevationM.toFixed(2)} m`} /><ReportMetric label="Pole top" value={pole.topHeightM == null ? "—" : `${pole.topHeightM.toFixed(2)} m`} /><ReportMetric label="Pole height" value={pole.poleHeightFt == null ? "—" : `${pole.poleHeightFt} ft`} /><ReportMetric label="Class" value={pole.poleClass ?? "—"} /></section><section className="report-schedule"><div><p>MEASUREMENTS</p><h2>Attachment schedule</h2><span>{pole.attachments.length} exact points</span></div><table><thead><tr><th>Attachment</th><th>Classification</th><th>Height above ground</th><th>Photo side</th></tr></thead><tbody>{pole.attachments.map((item) => <tr key={item.id}><td>{item.name}</td><td>{item.kind}</td><td><strong>{item.heightM.toFixed(3)} m</strong></td><td>{item.side}</td></tr>)}</tbody></table></section><footer className="report-footer"><span>Generated by Powertek Pole Portal</span><span>{new Date().toLocaleString("en-CA", { dateStyle: "medium", timeStyle: "short" })}</span></footer></article></main>;
}

function ReportMetric({ label, value }: { label: string; value: string }) { return <span><small>{label}</small><strong>{value}</strong></span>; }

