import { rawDb } from "@/db/raw";
import { requireProjectAccess } from "@/lib/portal-auth";
import { PrintButton } from "@/components/print-button";
import Link from "next/link";

export const dynamic = "force-dynamic";

export default async function PoleReportPage({ params }: { params: Promise<{ projectId: string; poleId: string }> }) {
  const { projectId, poleId } = await params;
  await requireProjectAccess(projectId);
  const db = rawDb();
  const pole = await db.prepare(`
    SELECT po.*, p.name AS project_name, p.code AS project_code, c.name AS client_name
    FROM poles po JOIN projects p ON p.id = po.project_id JOIN clients c ON c.id = p.client_id
    WHERE po.id = ? AND po.project_id = ?
  `).bind(poleId, projectId).first<Record<string, unknown>>();
  if (!pole) return <main className="report-page"><h1>Pole not found</h1></main>;
  const attachments = (await db.prepare(`SELECT name, height_m, side, kind FROM attachments WHERE pole_id = ? ORDER BY height_m DESC`).bind(poleId).all<Record<string, unknown>>()).results;
  return <main className="report-page">
    <header className="report-toolbar"><Link href={`/projects/${projectId}`}>← Return to project</Link><PrintButton /></header>
    <article className="report-sheet">
      <header className="report-brand"><span><i /><strong>POWERTEK</strong></span><p>POLE ATTACHMENT REPORT</p></header>
      <section className="report-title"><p>{String(pole.client_name)} / {String(pole.project_name)}</p><h1>{String(pole.pole_name)}</h1><span>Measured pole record</span></section>
      <section className="report-metrics">
        <ReportMetric label="Latitude" value={String(pole.latitude)} /><ReportMetric label="Longitude" value={String(pole.longitude)} /><ReportMetric label="Ground elevation" value={`${Number(pole.elevation_m).toFixed(2)} m AMSL`} />
        <ReportMetric label="Pole top" value={pole.top_height_m == null ? "—" : `${Number(pole.top_height_m).toFixed(2)} m`} /><ReportMetric label="Pole height" value={pole.pole_height_ft == null ? "—" : `${pole.pole_height_ft} ft`} /><ReportMetric label="Pole class" value={String(pole.pole_class ?? "—")} />
      </section>
      {Boolean(pole.image_key) && <section className="report-photo"><img src={`/api/projects/${projectId}/poles/${poleId}/image`} alt={`Measured pole ${String(pole.pole_name)}`} /></section>}
      <section className="report-schedule"><div><p>MEASUREMENTS</p><h2>Attachment schedule</h2><span>{attachments.length} exact points</span></div><table><thead><tr><th>Attachment</th><th>Classification</th><th>Height above ground</th><th>Photo side</th></tr></thead><tbody>{attachments.map((item, index) => <tr key={`${item.name}-${index}`}><td>{String(item.name)}</td><td>{String(item.kind)}</td><td><strong>{Number(item.height_m).toFixed(3)} m</strong></td><td>{String(item.side)}</td></tr>)}</tbody></table></section>
      <footer className="report-footer"><span>Generated by Powertek Pole Portal</span><span>{new Date().toLocaleString("en-CA", { dateStyle: "medium", timeStyle: "short" })}</span></footer>
    </article>
  </main>;
}

function ReportMetric({ label, value }: { label: string; value: string }) { return <span><small>{label}</small><strong>{value}</strong></span>; }
