import { ArrowRight, ArrowUpRight, Activity, Camera, Compass, Download, FileCheck2, Layers3, LockKeyhole, MapPinned, ShieldCheck, Zap } from "lucide-react";

const services = [
  { icon: Compass, title: "Transmission line modelling", tag: "DESIGN & ANALYSIS", body: "PLS-CADD modelling of conductors, structures, terrain, and aerial obstacles for informed line design." },
  { icon: Activity, title: "Thermal rating analysis", tag: "NETWORK CAPACITY", body: "Understand conductor temperatures and operating limits to make confident capacity decisions." },
  { icon: Layers3, title: "Vegetation risk management", tag: "LIDAR INTELLIGENCE", body: "Identify grow-in and tree-fall hazards with LiDAR data and PLS-CADD danger-tree analysis." },
  { icon: Camera, title: "High-resolution inspection", tag: "ASSET CONDITION", body: "Georeferenced imagery brings cracks, corrosion, and visible asset conditions into clear focus." },
  { icon: Zap, title: "Thermal IR surveys", tag: "FAULT DETECTION", body: "Radiometric inspection helps locate potential hot spots at structures and mid-span joints." },
  { icon: ShieldCheck, title: "Corona UV inspection", tag: "PREVENTIVE INSPECTION", body: "Solar-blind UV imaging detects discharge associated with damaged or loose components." },
];

function TowerArtwork() {
  return <svg className="tower-art" viewBox="0 0 640 600" fill="none" aria-hidden="true">
    <defs><linearGradient id="towerSky" x2="640" y2="600" gradientUnits="userSpaceOnUse"><stop stopColor="#132a80"/><stop offset="1" stopColor="#08184d"/></linearGradient><pattern id="towerGrid" width="40" height="40" patternUnits="userSpaceOnUse"><path d="M40 0H0V40" stroke="#fff" strokeOpacity=".055"/></pattern></defs>
    <rect width="640" height="600" fill="url(#towerSky)"/><rect width="640" height="600" fill="url(#towerGrid)"/>
    <circle cx="345" cy="245" r="170" stroke="#5b74c4" strokeOpacity=".2"/><circle cx="345" cy="245" r="215" stroke="#5b74c4" strokeOpacity=".15"/>
    <path d="M0 510 90 463 164 478 243 436 340 470 438 428 523 460 640 416V600H0Z" fill="#132961"/><path d="M0 557 150 493 245 522 390 480 503 516 640 477V600H0Z" fill="#0a1c4e"/>
    <g stroke="#c2cdee" strokeWidth="2.5" strokeLinejoin="round"><path d="M253 535 321 113H344L412 535M284 344H381M296 269H369M306 206H359M321 113 344 113M253 535 381 344 296 269 359 206 321 113M412 535 284 344 369 269 306 206 344 113M271 422H396M271 422 381 344M396 422 284 344M253 535H412"/><path d="M298 245H224L308 210M367 245H440L357 210M311 180H256L318 150M352 180H407L346 150M279 327H183L294 284M386 327H482L372 284"/></g>
    <g stroke="#839bdc" strokeWidth="1.2"><path d="M0 191Q111 232 256 187M407 187Q520 224 640 165M0 263Q100 304 224 252M440 252Q550 285 640 239M0 349Q82 391 183 335M482 335Q560 368 640 323"/></g>
    <g fill="#ff8d2a"><circle cx="256" cy="187" r="5"/><circle cx="407" cy="187" r="5"/><circle cx="224" cy="252" r="5"/><circle cx="440" cy="252" r="5"/><circle cx="183" cy="335" r="5"/><circle cx="482" cy="335" r="5"/></g>
    <path d="M440 252H535V210" stroke="#ff8d2a" strokeDasharray="4 5"/><rect x="445" y="163" width="154" height="46" rx="8" fill="#fff"/><text x="460" y="182" fill="#657087" fontFamily="Arial" fontSize="9" letterSpacing="1">ENGINEERING PRECISION</text><text x="460" y="198" fill="#10266e" fontFamily="Arial" fontSize="12" fontWeight="700">Every detail. In focus.</text>
  </svg>;
}

export function MarketingHome({ portalSignInUrl }: { portalSignInUrl: string }) {
  return <main className="brand-site" id="top">
    <header className="site-header"><a href="#top" aria-label="Powertek home"><img className="site-logo" src="/powertek-logo.svg" alt="Powertek Utility Services"/></a><nav aria-label="Main navigation"><a href="#services">Our expertise</a><a href="#approach">Our approach</a><a href="#workspace">Client workspace</a></nav><a className="brand-button navy" href={portalSignInUrl}><LockKeyhole size={15}/> Client sign in <ArrowUpRight size={16}/></a></header>
    <section className="site-hero"><div className="hero-content"><p className="brand-eyebrow"><span/> ENGINEERING A MORE RELIABLE NETWORK</p><h1>Clarity for every line.<br/><em>Confidence in<br/>every decision.</em></h1><p className="hero-description">From transmission engineering to aerial inspection, we turn complex field data into a clearer picture of your network.</p><div className="hero-buttons"><a className="brand-button orange" href="#services">Explore our expertise <ArrowRight size={18}/></a><a className="text-link" href="mailto:vnr@powertekecp.com">Let’s talk about your project <ArrowUpRight size={17}/></a></div><div className="hero-proof"><ShieldCheck size={20}/><p>Built for utility teams.<span>Precision in the field. Confidence at the desk.</span></p></div></div><div className="hero-illustration"><div className="art-label"><span className="live-dot"/> TRANSMISSION INTELLIGENCE <span>01 / FIELD VIEW</span></div><TowerArtwork/><div className="art-footer"><span><MapPinned size={17}/> From line to asset</span><span><Layers3 size={17}/> Data with context</span></div></div></section>
    <div className="expertise-strip"><span>ONE CONNECTED VIEW</span><p>Transmission engineering <i/> Aerial inspection <i/> Asset intelligence <i/> Secure project delivery</p></div>
    <section className="site-section" id="services"><div className="section-heading"><div><p className="brand-eyebrow">01 — OUR EXPERTISE</p><h2>Better insight.<br/>Stronger infrastructure.</h2></div><p>Specialist engineering and inspection services that help you understand asset condition, reduce risk, and plan what comes next.</p></div><div className="expertise-grid">{services.map(({icon: Icon, title, tag, body}, index)=><article key={title}><div className="service-top"><span><Icon size={24}/></span><small>0{index+1}</small></div><p className="service-tag">{tag}</p><h3>{title}</h3><p>{body}</p><a href={`mailto:vnr@powertekecp.com?subject=${encodeURIComponent(title + " enquiry")}`}>Discuss this service <ArrowUpRight size={18}/></a></article>)}</div></section>
    <section className="approach-section" id="approach"><div><p className="brand-eyebrow">02 — FROM FIELD TO DECISION</p><h2>Complex data.<br/><em>A clear way forward.</em></h2><p>Keep the big picture and the smallest detail in view. Our engineering and inspection work connects field records to practical project deliverables.</p><a className="text-link" href="#workspace">Discover your workspace <ArrowRight size={18}/></a></div><ol className="approach-steps"><li><span>01</span><div><h3>Capture the detail</h3><p>Georeferenced imagery, LiDAR, and measured asset records.</p></div><Camera/></li><li><span>02</span><div><h3>Understand the network</h3><p>Engineering models and inspection analysis with context.</p></div><Compass/></li><li><span>03</span><div><h3>Deliver with clarity</h3><p>Organized project data, reports, and original-quality files.</p></div><FileCheck2/></li></ol></section>
    <section className="site-section workspace-section" id="workspace"><div className="workspace-intro"><p className="brand-eyebrow">03 — YOUR CONNECTED WORKSPACE</p><h2>Your projects.<br/>One place to see it all.</h2><p>A secure workspace for your team to explore assigned projects, inspect pole records, and access the files you need.</p><div className="workspace-benefits"><span><MapPinned/> Mapped pole locations</span><span><Camera/> Original-resolution photos</span><span><Layers3/> Measured engineering profiles</span><span><Download/> Reports and project downloads</span></div><a className="brand-button navy" href={portalSignInUrl}>Open your client workspace <ArrowRight size={18}/></a></div><div className="portal-showcase" aria-label="Illustration of the client workspace"><header><img src="/powertek-logo.svg" alt="Powertek"/><span><ShieldCheck size={14}/> PRIVATE WORKSPACE</span></header><div className="showcase-body"><aside><span className="showcase-active"><Layers3 size={16}/> Projects</span><span><MapPinned size={16}/> Asset records</span><span><Download size={16}/> Deliverables</span></aside><div><p className="brand-eyebrow">PROJECT OVERVIEW · ILLUSTRATION</p><h3>Everything in view.</h3><div className="showcase-tiles"><span><MapPinned/><b>Locations</b><small>Explore in context</small></span><span><Camera/><b>Imagery</b><small>Review every detail</small></span></div><div className="showcase-record"><FileCheck2/><div><b>Survey deliverables</b><span>Maps, measurements, and reports</span></div><ShieldCheck/></div><p className="showcase-note"><LockKeyhole size={13}/> Access assigned by your administrator</p></div></div></div></section>
    <section className="site-contact"><div><p className="brand-eyebrow">LET’S BUILD A CLEARER PICTURE</p><h2>Your next project<br/>starts with a conversation.</h2><a className="brand-button orange" href="mailto:vnr@powertekecp.com">Get in touch <ArrowUpRight size={18}/></a></div><div className="contact-information"><a href="mailto:vnr@powertekecp.com"><small>EMAIL US</small><b>vnr@powertekecp.com</b></a><a href="tel:+919573263993"><small>CALL US</small><b>+91 95732 63993</b></a><p><small>FIND US</small>Plot No 56 &amp; 57, Road No 5/3<br/>Nizampet, Hyderabad 500090, India</p></div></section>
    <footer className="site-footer"><a href="#top"><img className="site-logo" src="/powertek-logo.svg" alt="Powertek Utility Services"/></a><p>Engineering insight. Reliable networks.</p><a href={portalSignInUrl}>Client sign in <ArrowUpRight size={14}/></a><small>© {new Date().getFullYear()} Powertek Utility Services</small></footer>
  </main>;
}
