import { Activity, ArrowDownToLine, ArrowRight, ArrowUpRight, Building2, Camera, Check, Compass, FileArchive, FileImage, FileText, LockKeyhole, MapPinned, Ruler, ShieldCheck } from "lucide-react";

function Brand() {
  return <span className="brand-lockup marketing-brand"><span className="brand-mark" aria-hidden="true"><span /></span><span><strong>POWERTEK</strong><small>UTILITY SERVICES</small></span></span>;
}

function SurveyPreview() {
  return <div className="marketing-preview" aria-label="Illustrative pole survey map and measurement preview">
    <div className="marketing-preview-bar"><span>PROJECT VIEW</span><span><i /> SECURE WORKSPACE</span></div>
    <div className="marketing-map">
      <div className="marketing-contour contour-1" /><div className="marketing-contour contour-2" /><div className="marketing-contour contour-3" />
      <svg viewBox="0 0 640 365" preserveAspectRatio="none" aria-hidden="true">
        <path className="marketing-road" d="M-30 281 C 92 258 127 207 214 221 S 365 287 444 209 S 538 124 674 103" />
        <path className="marketing-road-edge" d="M-30 281 C 92 258 127 207 214 221 S 365 287 444 209 S 538 124 674 103" />
        <path className="marketing-boundary" d="M90 30 L170 86 L166 174 L95 222 L37 166 L43 82Z" />
        <path className="marketing-boundary" d="M411 238 L488 185 L572 206 L604 280 L549 337 L456 319Z" />
      </svg>
      <span className="marketing-map-name">SURVEY AREA</span><span className="marketing-map-road">TRANSMISSION LINE</span>
      {["P-204", "P-205", "P-206", "P-207", "P-208"].map((pole, i) => <span key={pole} className={"marketing-pin mp-" + (i + 1)}><i />{pole}</span>)}
      <div className="marketing-measure-card"><small>SELECTED POLE</small><b>Selected asset <i>Example</i></b><div className="marketing-pole"><span /><i /><i /><i /></div><div><span>PRIMARY-1</span><strong>10.174 m</strong></div><div><span>NEUTRAL</span><strong>7.662 m</strong></div><div><span>COMM-1</span><strong>6.619 m</strong></div></div>
      <span className="marketing-map-scale">N <i /> 0 — 500 ft</span>
    </div>
    <div className="marketing-preview-foot"><span><MapPinned size={13} /> 76 POLES</span><span><Ruler size={13} /> MEASURED ATTACHMENTS</span><span><FileImage size={13} /> FULL-RES PHOTOS</span></div>
  </div>;
}

const services = [
  { icon: Compass, label: "01 / TRANSMISSION LINE MODELLING", title: <>PLS-CADD line<br />modelling.</>, body: "Model conductors, structures, terrain, and aerial obstacles to support line design, route changes, and optimization." },
  { icon: Activity, label: "02 / THERMAL RATING ANALYSIS", title: <>Understand line<br />capacity.</>, body: "Simulate operating conditions and conductor temperature against maximum rating limits." },
  { icon: MapPinned, label: "03 / VEGETATION MANAGEMENT", title: <>Find vegetation<br />risk early.</>, body: "Combine LiDAR and PLS-CADD danger-tree analysis to assess grow-in and simulated tree-fall hazards." },
  { icon: Camera, label: "04 / HIGH-RESOLUTION IMAGERY", title: <>A clear visual<br />asset record.</>, body: "Capture georeferenced imagery to review cracks, corrosion, chips, and other visible asset conditions." },
  { icon: Activity, label: "05 / THERMAL IR SURVEYS", title: <>Locate thermal<br />anomalies.</>, body: "Use radiometric thermal inspection to identify and quantify potential hot spots at structures and mid-span joints." },
  { icon: ShieldCheck, label: "06 / CORONA UV INSPECTION", title: <>See corona<br />discharge.</>, body: "Use solar-blind bi-spectral UV imaging to detect and classify discharge associated with damaged or loose components." },
];

export function MarketingHome({ portalSignInUrl }: { portalSignInUrl: string }) {
  return <main className="powertek-site" id="top">
    <header className="marketing-header"><a href="#top" className="marketing-logo" aria-label="Powertek home"><Brand /></a><nav><a href="#services">Services</a><a href="#workflow">How it works</a><a href="#workspace">Client workspace</a></nav><a className="marketing-login" href={portalSignInUrl} target="_top"><LockKeyhole size={14} /> Client sign in</a></header>
    <section className="marketing-hero"><div className="marketing-hero-copy"><p className="marketing-eyebrow"><i /> TRANSMISSION LINE ENGINEERING</p><h1>Reduce network risk.<br /><em>Lower maintenance costs.</em></h1><p className="marketing-lede">Engineering analysis, aerial inspection, and field data that help utility teams understand asset condition and plan reliable maintenance.</p><div className="marketing-actions"><a className="marketing-primary" href="#services">Explore services <ArrowRight size={16} /></a><a className="marketing-secondary" href={portalSignInUrl} target="_top"><span>↗</span> Open client portal</a></div><div className="marketing-assurance"><ShieldCheck size={15} /><span>Project access is assigned by your Powertek administrator.</span></div></div><div className="marketing-hero-art"><div className="marketing-glow" /><SurveyPreview /><div className="marketing-photo-card"><div className="marketing-photo-scene"><i /><b /><span /></div><span><Camera size={12} /> POLE P-206 <i /> MEASURED OVERLAY</span></div><div className="marketing-coordinate">REFERENCE VIEW<br />PROJECT DATA PRIVATE</div></div><a className="marketing-scroll" href="#services">SCROLL TO EXPLORE <span>↓</span></a></section>
    <section className="marketing-ribbon"><span>BUILT FOR UTILITY ASSET MANAGEMENT</span><div><span><MapPinned /> TRANSMISSION MODELLING</span><span><Ruler /> THERMAL & UV INSPECTION</span><span><Activity /> LIDAR VEGETATION ANALYSIS</span><span><FileArchive /> CONTROLLED DOWNLOADS</span></div></section>
    <section className="marketing-services" id="services"><div className="marketing-section-top"><div><p className="marketing-eyebrow"><i>01</i> POWERTEK SERVICES</p><h2>Engineering insight,<br /><em>from line to asset.</em></h2></div><p>Explore Powertek’s transmission-line engineering and inspection services, with project deliverables available through a secure client workspace.</p></div><div className="marketing-service-grid">{services.map(({ icon: Icon, label, title, body }) => <article key={label}><span className="marketing-service-icon"><Icon size={19} /></span><small>{label}</small><h3>{title}</h3><p>{body}</p><a href={portalSignInUrl} target="_top">View client portal <ArrowUpRight size={14} /></a></article>)}</div></section>
    <section className="marketing-process" id="workflow"><div className="marketing-process-art"><div className="process-map-card"><MapPinned size={16} /><span>PROJECT LOCATION</span><b>Find the pole in context</b><div className="process-map-lines" /><i className="process-pin" /></div><div className="process-photo-card"><span className="process-pole" /><i className="wire a" /><i className="wire b" /><i className="wire c" /><div><Camera size={12} /> MEASURED PHOTO</div></div><span className="process-arrow"><ArrowRight size={16} /></span><div className="process-file-card"><span><FileText /></span><b>Survey deliverables</b><small>Ready to review</small><div><Check size={12} /> PDF <Check size={12} /> CSV <Check size={12} /> ZIP</div></div></div><div className="marketing-process-copy"><p className="marketing-eyebrow"><i>02</i> FROM FIELD TO HANDOFF</p><h2>Inspection data<br />kept <em>in context.</em></h2><p>Powertek combines line modelling and aerial inspection with field records. Clients can securely review assigned maps, photos, measurement details, and deliverables in one workspace.</p><ul><li><Check /> Project access organized by client</li><li><Check /> Photo overlays with attachment measurements</li><li><Check /> Downloadable survey files and reports</li></ul></div></section>
    <section className="marketing-workspace" id="workspace"><div className="workspace-heading"><p className="marketing-eyebrow"><i>03</i> CLIENT WORKSPACE</p><h2>Your project, <em>all in one place.</em></h2><p>Sign in to view assigned projects, open mapped pole records, preview photos, and download your work.</p></div><div className="workspace-window"><div className="workspace-window-bar"><span><i /><i /><i /></span><b><LockKeyhole size={11} /> POWERTEK CLIENT PORTAL</b><small>JD</small></div><div className="workspace-preview"><div className="workspace-list"><span>PROJECTS</span><b><i /> Assigned sample project</b><small>Mapped assets · photo details</small><div /><b><i /> Browse pole records</b><small>Access is assigned by administrator</small></div><div className="workspace-pole-card"><div><small>SELECTED POLE</small><b>P-206 <i>2114585</i></b><span>Map preview · assigned project data</span></div><div className="workspace-photo"><span /><i /><b>MEASURED PHOTO OVERLAY</b></div><div className="workspace-measures"><span>Primary conductor <b>Measured</b></span><span>Neutral conductor <b>Measured</b></span><span>Communication <b>Measured</b></span></div></div><div className="workspace-downloads"><span>PROJECT FILES</span><b><FileText /> Survey report.pdf <ArrowDownToLine /></b><b><FileArchive /> Attachments.csv <ArrowDownToLine /></b><b><FileImage /> Pole photos.zip <ArrowDownToLine /></b></div></div><div className="workspace-window-foot"><span><ShieldCheck size={13} /> PRIVATE PROJECT ACCESS</span><span>MAPS <i /> POLE DATA <i /> PHOTOS <i /> FILES</span></div></div><a className="workspace-login" href={portalSignInUrl} target="_top">Sign in to your client workspace <ArrowRight size={15} /></a></section>
    <section className="marketing-contact"><div><p className="marketing-eyebrow"><i>04</i> WORK WITH POWERTEK</p><h2>Have a project<br />to put <em>in view?</em></h2><p>For a project conversation or portal access, connect with your Powertek contact. Existing clients can sign in to their workspace at any time.</p></div><a href={portalSignInUrl} target="_top">Client sign in <ArrowUpRight size={17} /></a><div className="contact-grid" /></section>
    <footer className="marketing-footer"><a href="#top" aria-label="Powertek home"><Brand /></a><span>TRANSMISSION ENGINEERING · AERIAL INSPECTION · PROJECT DELIVERY</span><div><a href="#services">Services</a><a href="#workflow">How it works</a><a href={portalSignInUrl} target="_top">Client sign in</a></div><small>© {new Date().getFullYear()} Powertek</small></footer>
  </main>;
}